[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ec3api = { path="../../ec3api" }
egui-notify = "0.14"
rusqlite = { version = "0.30.0", features = ["bundled"] }
